version: "3.3"

services:
  healthpal:
    ports:
      - 3000:3000
    build:
      context: healthpal
      dockerfile: Dockerfile
    volumes:
      - ./healthpal:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
